---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hapi-fhir-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: hapi-fhir-jpaserver
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
      - cdr
  rules:
    - host: cdr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hapi-fhir-jpaserver
                port:
                  number: 8080
