apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-test.yaml
  - 01-helm-repositories.yaml
  - 02-hapi-fhir-release.yaml
  - 02-hapi-fhir-service.yaml
  - 03-hapi-fhir-ingress.yaml